### ISSUE TITLE
Strict-Transport-Security header not being added on SSL requests

### ISSUE THREAD

**Issue by jamesmacwhite** [GetPageSpeed/ngx_security_headers#12]
NGINX 1.18.0

I tested this module out and while it did add all other security headers, the `Strict-Transport-Security` header was not output.

I have a server block defined with listen directives for SSL, configured with a valid LetsEncrypt certificate.

I can only assume this condition for whatever reason does not detect an SSL request.

https://github.com/GetPageSpeed/ngx_security_headers/blob/master/src/ngx_http_security_headers_module.c#L258-L265

> nginx version: nginx/1.18.0 (Ubuntu)
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-KTLRnK/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-compat --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module

**Comment by jamesmacwhite** [comment]
Testing on a HTTPS request for sure, the header is not output on any SSL requests. I can only assume the condition for checking SSL is not evaluating true for whatever reason.

I do have multiple listen directives, because traffic to nginx is being proxied via proxy_protocol through haproxy, however I have separate listen bindings for local usage, which are doing the same.

**Comment by jamesmacwhite** [comment]
In the end I've used the HTTP more headers module and created an include that is added to every virtualhost block.

It's better than the add_header directive, but obviously not as clean as just adding to the http block.

For whatever reason I can only assume that `r->connection->ssl` is not returning true for your modules check and hence the header does not get added.

It seems specific to this header, because all the others get added, so the module is loaded and working, but the condition for `Strict-Transport-Security` does not enable it.

**Comment by dvershinin** [comment]
Indeed, if there's HAPROXY or e.g. Hitch doing the TLS, the `r->connection->ssl` would be false, as this is set only for when NGINX is the one doing encryption.

Added equivalent check that should be checking request protocol, not the connection protocol, thus will succeed for a case when the connection to NGINX comes from a TLS terminator.

**Comment by jamesmacwhite** [comment]
In my case I have HAProxy forwarding the TCP connection with send_proxy_v2, but this is for external traffic, internally in my LAN this is bypassed and connects to NGINX directly with the PROXY protocol, which still seemed to not show the Strict-Transport-Security header, but I'll recompile and test for you and see if the new change works.

**Comment by jamesmacwhite** [comment]
Interestingly, compiling the latest module code, the Strict-Transport-Security header is still not output on SSL/TLS requests. Does having http2 enabled have anything to do with it? I can't see what could be the issue. HAProxy should not be involved for any local request I'm doing in the LAN, I have a local IPv4 and IPv6 listen setup which will bypass HAProxy internally.

**Comment by dvershinin** [comment]
> compiling the latest module code

That was it. You probably compiled with*out* OpenSSL and the relevant code simply wasn't included.

It was fixed in v.0.0.11: since we don't check connection protocol for adding the header, but only checking URL protocol, it's fine now to enable adding header without requiring OpenSSL.

For anyone compiling, added notes to README and potential pitfalls compared to packaged install.

**Comment by jamesmacwhite** [comment]
Thanks for the change. I'm still not sure the issue was that though, note that the original output states it was compiled with OpenSSL:

```
nginx version: nginx/1.18.0 (Ubuntu)
built with OpenSSL 1.1.1f 31 Mar 2020
TLS SNI support enabled
```
